### ISSUE TITLE
Awesome Readme

### ISSUE THREAD

**Issue by IanDCarroll** [IanDCarroll/FSLA#11]
As a product owner of a free open-source project, I want a README that allows anyone to get the app running locally on their browsers/code editors, so we can get them to work on issues ASAP. 

https://www.pivotaltracker.com/story/show/128461683

**Comment by machikoyasuda** [comment]
Wooooooot 

Also, Ian, you are the chief documentarian and editorial writer :)

**Comment by IanDCarroll** [comment]
I figured those would go to the SM...

**Comment by machikoyasuda** [comment]
I always start with every GitHub repo by putting the URL of the project in this spot here 
![screenshot 2016-08-16 12 17 09](https://cloud.githubusercontent.com/assets/3673236/17712562/639f9ad4-63ab-11e6-863f-303d14344fa6.png)

If you could go thru and make the README super understandable for everyone.. maybe this could become a Tutorial for future Fullstackers

**Comment by IanDCarroll** [comment]
URL added.

**Comment by IanDCarroll** [comment]
@machikoyasuda please check the README outline so far. 
Before I fill in the content, is there anything I'm missing?
https://github.com/IanDCarroll/FSLA/tree/gh-pages

**Comment by machikoyasuda** [comment]
Usually a backlog is a tag that you add to ticket/issue. It is not an issue itself. 

Can you add the README stuff to master branch, not just gh pages branch? I got lost!

i really love the headings so far. but thats a lot of content. i would start smaller.

**Comment by machikoyasuda** [comment]
And it is best to leave me comments in line like this https://github.com/IanDCarroll/FSLA/commit/aa59651918049b8664cfec0fc9471812a66bc904#commitcomment-18662924

That way, I can see the comment/question and the code/text together.

**Comment by IanDCarroll** [comment]
@machikoyasuda I'll get all branches updated before getting your attention. Also, I'll leave comments inline. (didn't know you could do that!)

Also, How would you groom the backlog and keep it in good shape if it's all spread out as tags? How would you know what their order is? Would you include the whole thing as a .md in the code and add links to the issues where those are being worked on?

**Comment by machikoyasuda** [comment]
@IanDCarroll use Pivotal Tracker to keep the Backlog groomed.

**Comment by IanDCarroll** [comment]
@machikoyasuda Is there some way to do this without having to spend money? Is Trello ok to use instead?

**Comment by machikoyasuda** [comment]
@IanDCarroll aren't open source projects free on pivotal tracker or no? trello is okay too. use whatevers free. usually if its open source, its free. (github is like taht).

**Comment by machikoyasuda** [comment]
@IanDCarroll yup 
![screenshot 2016-08-16 14 40 40](https://cloud.githubusercontent.com/assets/3673236/17716850/6c58e298-63bf-11e6-9ba4-9d8c1855a1ba.png) professionals use PT or Jira in the office.. so those would be good learn/get used to :)

**Comment by IanDCarroll** [comment]
Ok, setting PT up...

**Comment by IanDCarroll** [comment]
@machikoyasuda Ok, this is basically done. There are a few more features to add to the README, those are tracked in #16 and #17 .

**Comment by IanDCarroll** [comment]
New wording for the story. I might need to revise this so that the above can happen. That might be a job partly for #17

**Comment by IanDCarroll** [comment]
Done! Moving this to the "Product Increment!" AKA "Closed Issues"
