### ISSUE TITLE
Create getting started section of README.md

### ISSUE THREAD

**Issue by IanDCarroll** [IanDCarroll/FSLA#17]
As a new developer, I'd like a list of instructions on what to do to get myself ready to scrum on this project so I can get to having fun pairing and building awesome stuff. https://www.pivotaltracker.com/story/show/128467197

**Comment by machikoyasuda** [comment]
How to test: Once you do the README.md, try to get someone new to test it out. Have someone read your README and try to get them to replicate the repo and get started, but without you saying anything. If they trip up on something, add screenshots or add more instruction.

**Comment by IanDCarroll** [comment]
Also to do: fix the typo on line 36.

**Comment by IanDCarroll** [comment]
V 1.0 is ready to roll!
