### ISSUE TITLE
When the viewport is too narrow, the meetup list breaks.

### ISSUE THREAD

**Issue by xuhdev** [IanDCarroll/FSLA#26]
When the viewport is too narrow, the meetup list breaks.

Vimperator: http://www.vimperator.org/vimperator

**Comment by xuhdev** [comment]
https://www.topbug.net/blog/2016/08/19/why-is-open-source-beneficial-for-economic-growth-in-the-long-run/

**Comment by IanDCarroll** [comment]
Great work @xuhdev, @benjaminma! It was a treat watching you pair, I learned a lot :smile:

**Comment by IanDCarroll** [comment]
Here's the story:

As an on-the-go user, I would like to be able to have the site work on my phone, so that I can use it as a reference (while my vehicle is stopped) while I'm travelling.
